title: 둘도서관
description: 둘도서관 입니다.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://html.jiny.dev" # the base hostname & protocol for your site, e.g. http://example.com

source: src
destination: docs

layout:
  bgcolor: "#c8e6c9"
  width: "1200px"

sass:
  load_paths:
    - _scss
    - ../node_modules/bootstrap/scss

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap